format_version: 10
environments:
  terraform-aws-env:
    pipelines:
      - terraform-aws
pipelines:
  terraform-aws: # definition of mypipe1 pipeline
    group: tf-cloud
    display_order: -1
    label_template: "${COUNT}"
    lock_behavior: unlockWhenFinished
    environment_variables:
      INPUT_TF_ACTIONS_VERSION: 1.3.3

    materials:
      git: # this is the name of material, the name can contain only of alphanumeric & underscore characters
        git: https://github.com/dragosstan2602/terraform_aws.git
        branch: main
        auto_update: true
        ignore:
          - gocd_pipelines
#      terraform-task:
#        pipeline: terraform-aws
#        stage: make-artifact
#        ignore_for_scheduling: true
    stages: # list of stages in order
      - TF-PLAN:
          fetch_materials: true
          clean_workspace: true
          keep_artifacts: true
          approval:
            type: success
            allow_only_on_success: true

          jobs:
            tf-plan: # name of the job
              resources:
               - tf-aws
              tabs:
#                report: test-reports/index.html
                tf-plan: tf/report/plan.txt
              tasks: # ordered list of tasks to execute in job csharp
                - exec:
                    command: /bin/bah
                    arguments:
                      - -c
                      - git clone https://github.com/dragosstan2602/terraform_scripts.git
                    run_if: passed
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - chmod -R +x ~/terraform_scripts/
                    run_if: passed
                - exec: # indicates type of task
                    command: /bin/bash
                    arguments:
                      - -c
                      - ~/terraform_scripts/main.sh
                    run_if: passed
      - TF-APPLY:
          fetch_materials: true
          clean_workspace: true
          keep_artifacts: true
          approval:
            type: manual
            allow_only_on_success: true

          jobs:
            tf-apply: # name of the job
              resources:
                - tf-aws
              tabs:
                tf-plan: tf/report/apply.txt
              tasks: # ordered list of tasks to execute in job csharp
                - exec:
                    command: /bin/bah
                    arguments:
                      - -c
                      - git clone https://github.com/dragosstan2602/terraform_scripts.git
                    run_if: passed
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - chmod -R +x ~/terraform_scripts/
                    run_if: passed
                - exec: # indicates type of task
                    command: /bin/bash
                    arguments:
                      - -c
                      - ~/terraform_scripts/apply.sh
                    run_if: passed

